version: '3'
services:
  beatworm-server:
    build: ./server
    command: npm run start:dev
    volumes:
      - ./server:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      PG_HOST: postgres

  postgres:
    image: postgres:9.6.8-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: samcatherman
      POSTGRES_DB: beatworm_dev

  nginx:
    image: nginx:latest
    depends_on:
      - beatworm-server
    ports:
      - "80:80"
      - "443:443"
      - "8080:443"
    volumes:
      - ./nginx/beatworm.conf:/etc/nginx/conf.d/beatworm.conf
      - client-dist:/opt/local/beatworm-ui

  beatworm-ui:
    build: ./client
    # TODO: figure out how to get webpack-dev-server working instead of webpack --watch.
    #         webpack-dev-server seems to not change the files in any container/volume.
    command: npm run build-watch
    volumes:
      - ./client/src:/usr/src/src
      - client-dist:/usr/src/dist

volumes:
  client-dist:
