version: '3'
services:
  beatworm-server:
    build: ./server
    command: npm run start:dev
    volumes:
      - ./server:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      PG_HOST: postgres

  postgres:
    image: postgres:9.6.8-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: samcatherman
      POSTGRES_DB: beatworm_dev

  nginx:
    image: nginx:latest
    depends_on:
      - beatworm-server
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/app/client
      - ./nginx/beatworm.conf:/etc/nginx/conf.d/beatworm.conf

